#include "pg/shader/Target.h"

#include <algorithm>
#include <cctype>
#include <sstream>

namespace pg::shader {
namespace {

bool isIdentStart(char c) { return std::isalpha(static_cast<unsigned char>(c)) || c == '_'; }
bool isIdentChar(char c) { return std::isalnum(static_cast<unsigned char>(c)) || c == '_'; }
bool isDigit(char c) { return std::isdigit(static_cast<unsigned char>(c)) != 0; }

bool contains(const std::vector<std::string>& v, const std::string& s) {
    return std::find(v.begin(), v.end(), s) != v.end();
}

std::string join(const std::vector<std::string>& parts, const char* sep) {
    std::string out;
    for (size_t i = 0; i < parts.size(); ++i) {
        if (i) out += sep;
        out += parts[i];
    }
    return out;
}

const char* kHeader = "Generated by pgshader from a shader graph. Do not edit: edit the graph.";

/// The renderer-owned uniforms, in the order they sit in a uniform block.
struct BuiltinUniform {
    const char* name;
    const char* glslType;
    const char* hlslType;
    const char* global;  ///< the global that needs it, or nullptr if always needed
};
constexpr BuiltinUniform kBuiltins[] = {
    {"u_model", "mat4", "float4x4", nullptr},
    {"u_viewProj", "mat4", "float4x4", nullptr},
    {"u_cameraPos", "vec3", "float3", "view"},
    {"u_time", "float", "float", "time"},
    {"u_lightDir", "vec3", "float3", "light"},
};

/// std140 base alignment and size, in bytes.
void std140(const std::string& glslType, int& align, int& size) {
    if (glslType == "float") { align = 4; size = 4; }
    else if (glslType == "vec2") { align = 8; size = 8; }
    else if (glslType == "vec3") { align = 16; size = 12; }
    else if (glslType == "mat4") { align = 16; size = 64; }
    else { align = 16; size = 16; }  // vec4
}

// ---------------------------------------------------------------------------
// GLSL: OpenGL 3.3 core, OpenGL ES 3.0, and Vulkan (GLSL 450 -> SPIR-V).
// ---------------------------------------------------------------------------

class GlslTarget : public Target {
public:
    enum class Flavor { Gl330, Es300, Vulkan };
    explicit GlslTarget(Flavor f) : flavor_(f) {}

    std::string name() const override {
        switch (flavor_) {
            case Flavor::Gl330:  return "glsl330";
            case Flavor::Es300:  return "gles300";
            case Flavor::Vulkan: return "vulkan";
        }
        return "?";
    }

    std::string description() const override {
        switch (flavor_) {
            case Flavor::Gl330:  return "OpenGL 3.3 core (GLSL 330)";
            case Flavor::Es300:  return "OpenGL ES 3.0 / WebGL 2 (GLSL ES 300)";
            case Flavor::Vulkan: return "Vulkan (GLSL 450, compile to SPIR-V)";
        }
        return "?";
    }

    std::vector<ShaderFile> assemble(const Assembly& a) const override {
        return {file(a, Stage::Vertex), file(a, Stage::Fragment)};
    }

private:
    bool vulkan() const { return flavor_ == Flavor::Vulkan; }

    ShaderFile file(const Assembly& a, Stage stage) const {
        const bool vs = stage == Stage::Vertex;
        const StageBody& body = vs ? a.vertex : a.fragment;
        std::ostringstream o;

        switch (flavor_) {
            case Flavor::Gl330:  o << "#version 330 core\n"; break;
            case Flavor::Es300:  o << "#version 300 es\n"; break;
            case Flavor::Vulkan: o << "#version 450\n"; break;
        }
        o << "// " << kHeader << "\n// Target: " << description() << ", " << stageName(stage)
          << " stage.\n\n";
        if (flavor_ == Flavor::Es300) o << "precision highp float;\n\n";

        uniforms(o, a, body, vs);
        interface(o, a, vs);

        for (const auto& f : body.functions) o << f << '\n';

        o << "void main()\n{\n";
        if (vs) vertexMain(o, a, body);
        else fragmentMain(o, a, body);
        o << "}\n";
        return ShaderFile{vs ? ".vert" : ".frag", o.str(), {{stage, "main"}}};
    }

    void uniforms(std::ostringstream& o, const Assembly& a, const StageBody& body, bool vs) const {
        if (vulkan()) {
            // Vulkan has no loose uniforms: everything numeric lives in one
            // std140 block shared by both stages. The offsets are what the
            // application's struct must match.
            o << "layout(set = 0, binding = 0, std140) uniform Globals\n{\n";
            int cursor = 0;
            auto member = [&](const std::string& type, const std::string& name) {
                int align = 0, size = 0;
                std140(type, align, size);
                cursor = (cursor + align - 1) / align * align;
                o << "    " << type << ' ' << name << ";  // offset " << cursor << '\n';
                cursor += size;
            };
            for (const auto& b : kBuiltins) member(b.glslType, b.name);
            for (const auto& u : a.uniforms) {
                if (u.type != Type::Sampler2D) member(typeName(u.type), u.name);
            }
            o << "};  // " << cursor << " bytes\n";
            for (const auto& u : a.uniforms) {
                if (u.type == Type::Sampler2D && contains(body.uniforms, u.name)) {
                    o << "layout(set = 0, binding = " << (u.binding + 1) << ") uniform sampler2D "
                      << u.name << ";\n";
                }
            }
            o << '\n';
            return;
        }
        bool any = false;
        for (const auto& b : kBuiltins) {
            const bool needed = b.global ? (vs ? a.vertexUses(b.global) : a.fragmentUses(b.global)) : vs;
            if (!needed) continue;
            o << "uniform " << b.glslType << ' ' << b.name << ";\n";
            any = true;
        }
        for (const auto& u : a.uniforms) {
            if (!contains(body.uniforms, u.name)) continue;
            o << "uniform " << typeName(u.type) << ' ' << u.name << ";\n";
            any = true;
        }
        if (any) o << '\n';
    }

    /// Vertex attributes, the vertex -> fragment varyings and the colour output.
    void interface(std::ostringstream& o, const Assembly& a, bool vs) const {
        auto varying = [&](int location, const char* type, const char* name) {
            if (vulkan()) o << "layout(location = " << location << ") ";
            o << (vs ? "out " : "in ") << type << ' ' << name << ";\n";
        };
        if (vs) {
            o << "layout(location = 0) in vec3 a_position;\n";
            if (needsNormal(a)) o << "layout(location = 1) in vec3 a_normal;\n";
            if (needsUv(a)) o << "layout(location = 2) in vec2 a_uv;\n";
        }
        if (a.hasVarying("position")) varying(0, "vec3", "v_position");
        if (a.hasVarying("normal")) varying(1, "vec3", "v_normal");
        if (a.hasVarying("uv")) varying(2, "vec2", "v_uv");
        if (!vs) o << "layout(location = 0) out vec4 o_color;\n";
        o << '\n';
    }

    static bool needsNormal(const Assembly& a) { return a.vertexUses("normal") || a.hasVarying("normal"); }
    static bool needsUv(const Assembly& a) { return a.vertexUses("uv") || a.hasVarying("uv"); }

    void statements(std::ostringstream& o, const StageBody& body) const {
        for (const auto& s : body.statements) {
            o << "    " << typeName(s.type) << ' ' << s.name << " = " << s.expression << ";\n";
        }
    }

    void vertexMain(std::ostringstream& o, const Assembly& a, const StageBody& body) const {
        o << "    vec3 g_position = (u_model * vec4(a_position, 1.0)).xyz;\n";
        if (needsNormal(a)) o << "    vec3 g_normal = normalize(mat3(u_model) * a_normal);\n";
        if (needsUv(a)) o << "    vec2 g_uv = a_uv;\n";
        if (a.vertexUses("view")) o << "    vec3 g_view = normalize(u_cameraPos - g_position);\n";
        if (a.vertexUses("light")) o << "    vec3 g_light = normalize(u_lightDir);\n";
        if (a.vertexUses("time")) o << "    float g_time = u_time;\n";
        statements(o, body);
        if (!body.result.empty()) o << "    g_position += " << body.result << ";\n";
        if (a.hasVarying("position")) o << "    v_position = g_position;\n";
        if (a.hasVarying("normal")) o << "    v_normal = g_normal;\n";
        if (a.hasVarying("uv")) o << "    v_uv = g_uv;\n";
        o << "    gl_Position = u_viewProj * vec4(g_position, 1.0);\n";
    }

    void fragmentMain(std::ostringstream& o, const Assembly& a, const StageBody& body) const {
        if (a.fragmentUses("position")) o << "    vec3 g_position = v_position;\n";
        if (a.fragmentUses("normal")) o << "    vec3 g_normal = normalize(v_normal);\n";
        if (a.fragmentUses("uv")) o << "    vec2 g_uv = v_uv;\n";
        if (a.fragmentUses("view")) o << "    vec3 g_view = normalize(u_cameraPos - v_position);\n";
        if (a.fragmentUses("light")) o << "    vec3 g_light = normalize(u_lightDir);\n";
        if (a.fragmentUses("time")) o << "    float g_time = u_time;\n";
        statements(o, body);
        o << "    o_color = " << body.result << ";\n";
    }

    Flavor flavor_;
};

// ---------------------------------------------------------------------------
// HLSL: Direct3D 11/12, shader model 5. One file, two entry points.
// ---------------------------------------------------------------------------

class HlslTarget : public Target {
public:
    std::string name() const override { return "hlsl"; }
    std::string description() const override { return "Direct3D 11/12 (HLSL, shader model 5)"; }

    std::string typeName(Type t) const override {
        switch (t) {
            case Type::Float:     return "float";
            case Type::Vec2:      return "float2";
            case Type::Vec3:      return "float3";
            case Type::Vec4:      return "float4";
            case Type::Sampler2D: return "Texture2D";
            case Type::Any:       return "float";
        }
        return "float";
    }

    std::string translate(const std::string& code) const override {
        static const std::map<std::string, std::string> renames = {
            {"vec2", "float2"},       {"vec3", "float3"},     {"vec4", "float4"},
            {"ivec2", "int2"},        {"ivec3", "int3"},      {"ivec4", "int4"},
            {"bvec2", "bool2"},       {"bvec3", "bool3"},     {"bvec4", "bool4"},
            {"mat2", "float2x2"},     {"mat3", "float3x3"},   {"mat4", "float4x4"},
            {"mix", "lerp"},          {"fract", "frac"},      {"inversesqrt", "rsqrt"},
            {"dFdx", "ddx"},          {"dFdy", "ddy"},        {"mod", "fmod"},
        };
        return renameIdentifiers(code, renames);
    }

    std::string construct(Type t, const std::vector<std::string>& args) const override {
        return typeName(t) + "(" + join(args, ", ") + ")";
    }

    std::string splat(Type t, const std::string& scalar) const override {
        return "((" + typeName(t) + ")(" + scalar + "))";
    }

    std::vector<ShaderFile> assemble(const Assembly& a) const override {
        std::ostringstream o;
        o << "// " << kHeader << "\n// Target: " << description()
          << ". Entry points: vs_main, ps_main.\n\n";

        o << "cbuffer Globals : register(b0)\n{\n";
        for (const auto& b : kBuiltins) o << "    " << b.hlslType << ' ' << b.name << ";\n";
        for (const auto& u : a.uniforms) {
            if (u.type != Type::Sampler2D) o << "    " << typeName(u.type) << ' ' << u.name << ";\n";
        }
        o << "};\n\n";
        bool textures = false;
        for (const auto& u : a.uniforms) {
            if (u.type != Type::Sampler2D) continue;
            o << "Texture2D " << u.name << " : register(t" << u.binding << ");\n";
            o << "SamplerState " << u.name << "_sampler : register(s" << u.binding << ");\n";
            textures = true;
        }
        if (textures) o << '\n';

        const bool normal = a.vertexUses("normal") || a.hasVarying("normal");
        const bool uv = a.vertexUses("uv") || a.hasVarying("uv");
        o << "struct VSInput\n{\n    float3 a_position : POSITION;\n";
        if (normal) o << "    float3 a_normal : NORMAL;\n";
        if (uv) o << "    float2 a_uv : TEXCOORD0;\n";
        o << "};\n\n";
        o << "struct VSOutput\n{\n    float4 position : SV_Position;\n";
        if (a.hasVarying("position")) o << "    float3 v_position : TEXCOORD0;\n";
        if (a.hasVarying("normal")) o << "    float3 v_normal : TEXCOORD1;\n";
        if (a.hasVarying("uv")) o << "    float2 v_uv : TEXCOORD2;\n";
        o << "};\n\n";

        // One file serves both stages, so it carries the helpers of both.
        std::vector<std::string> functions = a.vertex.functions;
        for (const auto& f : a.fragment.functions) {
            if (!contains(functions, f)) functions.push_back(f);
        }
        for (const auto& f : functions) o << f << '\n';

        o << "VSOutput vs_main(VSInput input)\n{\n    VSOutput output;\n";
        o << "    float3 g_position = mul(u_model, float4(input.a_position, 1.0)).xyz;\n";
        if (normal) o << "    float3 g_normal = normalize(mul((float3x3)u_model, input.a_normal));\n";
        if (uv) o << "    float2 g_uv = input.a_uv;\n";
        if (a.vertexUses("view")) o << "    float3 g_view = normalize(u_cameraPos - g_position);\n";
        if (a.vertexUses("light")) o << "    float3 g_light = normalize(u_lightDir);\n";
        if (a.vertexUses("time")) o << "    float g_time = u_time;\n";
        statements(o, a.vertex);
        if (!a.vertex.result.empty()) o << "    g_position += " << a.vertex.result << ";\n";
        if (a.hasVarying("position")) o << "    output.v_position = g_position;\n";
        if (a.hasVarying("normal")) o << "    output.v_normal = g_normal;\n";
        if (a.hasVarying("uv")) o << "    output.v_uv = g_uv;\n";
        o << "    output.position = mul(u_viewProj, float4(g_position, 1.0));\n";
        o << "    return output;\n}\n\n";

        o << "float4 ps_main(VSOutput input) : SV_Target\n{\n";
        if (a.fragmentUses("position")) o << "    float3 g_position = input.v_position;\n";
        if (a.fragmentUses("normal")) o << "    float3 g_normal = normalize(input.v_normal);\n";
        if (a.fragmentUses("uv")) o << "    float2 g_uv = input.v_uv;\n";
        if (a.fragmentUses("view")) {
            o << "    float3 g_view = normalize(u_cameraPos - input.v_position);\n";
        }
        if (a.fragmentUses("light")) o << "    float3 g_light = normalize(u_lightDir);\n";
        if (a.fragmentUses("time")) o << "    float g_time = u_time;\n";
        statements(o, a.fragment);
        o << "    return " << a.fragment.result << ";\n}\n";

        return {ShaderFile{".hlsl", o.str(), {{Stage::Vertex, "vs_main"}, {Stage::Fragment, "ps_main"}}}};
    }

private:
    void statements(std::ostringstream& o, const StageBody& body) const {
        for (const auto& s : body.statements) {
            o << "    " << typeName(s.type) << ' ' << s.name << " = " << s.expression << ";\n";
        }
    }
};

}  // namespace

// --- Assembly ----------------------------------------------------------------

bool Assembly::fragmentUses(const std::string& g) const { return contains(fragment.globals, g); }
bool Assembly::vertexUses(const std::string& g) const { return contains(vertex.globals, g); }
bool Assembly::hasVarying(const std::string& v) const { return contains(varyings, v); }

// --- Target ------------------------------------------------------------------

std::string Target::typeName(Type t) const { return pg::shader::typeName(t); }

std::string Target::translate(const std::string& neutralCode) const { return neutralCode; }

std::string Target::construct(Type t, const std::vector<std::string>& args) const {
    return typeName(t) + "(" + join(args, ", ") + ")";
}

std::string Target::splat(Type t, const std::string& scalar) const {
    return typeName(t) + "(" + scalar + ")";
}

std::string Target::convert(const std::string& expr, Type from, Type to) const {
    if (from == to || !isNumeric(from) || !isNumeric(to)) return expr;
    const int have = componentCount(from), want = componentCount(to);
    if (have == 1) return splat(to, expr);
    if (want < have) {
        const bool simple = std::all_of(expr.begin(), expr.end(), isIdentChar);
        return (simple ? expr : "(" + expr + ")") + "." + std::string("xyzw").substr(0, static_cast<size_t>(want));
    }
    std::vector<std::string> args{expr};
    for (int i = have; i < want; ++i) args.push_back(i == 3 ? "1.0" : "0.0");
    return construct(to, args);
}

std::string Target::literal(const Value& v, Type t) const {
    const Value x = v.as(t);
    const int n = componentCount(t);
    if (n <= 1) {
        const std::string s = formatFloat(x.v[0]);
        return s[0] == '-' ? "(" + s + ")" : s;  // safe next to a binary minus
    }
    std::vector<std::string> args;
    for (int i = 0; i < n; ++i) args.push_back(formatFloat(x.v[static_cast<size_t>(i)]));
    return construct(t, args);
}

// --- registry ----------------------------------------------------------------

TargetRegistry::TargetRegistry() {
    add(makeGlsl330Target());
    add(makeGles300Target());
    add(makeVulkanTarget());
    add(makeHlslTarget());
}

TargetRegistry& TargetRegistry::instance() {
    static TargetRegistry r;
    return r;
}

void TargetRegistry::add(std::unique_ptr<Target> target) {
    if (!target) return;
    for (auto& t : targets_) {
        if (t->name() == target->name()) {
            t = std::move(target);
            return;
        }
    }
    targets_.push_back(std::move(target));
}

const Target* TargetRegistry::find(const std::string& name) const {
    for (const auto& t : targets_) {
        if (t->name() == name) return t.get();
    }
    return nullptr;
}

std::vector<const Target*> TargetRegistry::all() const {
    std::vector<const Target*> out;
    for (const auto& t : targets_) out.push_back(t.get());
    return out;
}

std::unique_ptr<Target> makeGlsl330Target() {
    return std::make_unique<GlslTarget>(GlslTarget::Flavor::Gl330);
}
std::unique_ptr<Target> makeGles300Target() {
    return std::make_unique<GlslTarget>(GlslTarget::Flavor::Es300);
}
std::unique_ptr<Target> makeVulkanTarget() {
    return std::make_unique<GlslTarget>(GlslTarget::Flavor::Vulkan);
}
std::unique_ptr<Target> makeHlslTarget() { return std::make_unique<HlslTarget>(); }

// --- helpers -----------------------------------------------------------------

std::string renameIdentifiers(const std::string& code,
                              const std::map<std::string, std::string>& renames) {
    std::string out;
    out.reserve(code.size() + code.size() / 8);
    const size_t n = code.size();
    size_t i = 0;
    char lastSignificant = 0;  // last non-space character copied
    auto copy = [&](size_t from, size_t to) {
        out.append(code, from, to - from);
        for (size_t k = to; k > from; --k) {
            if (!std::isspace(static_cast<unsigned char>(code[k - 1]))) {
                lastSignificant = code[k - 1];
                break;
            }
        }
    };
    while (i < n) {
        const char c = code[i];
        if (c == '/' && i + 1 < n && code[i + 1] == '/') {  // line comment
            size_t j = code.find('\n', i);
            j = j == std::string::npos ? n : j;
            copy(i, j);
            i = j;
        } else if (c == '/' && i + 1 < n && code[i + 1] == '*') {  // block comment
            size_t j = code.find("*/", i + 2);
            j = j == std::string::npos ? n : j + 2;
            copy(i, j);
            i = j;
        } else if (isDigit(c) || (c == '.' && i + 1 < n && isDigit(code[i + 1]))) {  // number
            size_t j = i + 1;
            while (j < n && (isIdentChar(code[j]) || code[j] == '.' ||
                             ((code[j] == '+' || code[j] == '-') &&
                              (code[j - 1] == 'e' || code[j - 1] == 'E')))) {
                ++j;
            }
            copy(i, j);
            i = j;
        } else if (isIdentStart(c)) {
            size_t j = i + 1;
            while (j < n && isIdentChar(code[j])) ++j;
            const std::string id = code.substr(i, j - i);
            auto it = renames.find(id);
            if (it != renames.end() && lastSignificant != '.') {
                out += it->second;
                lastSignificant = it->second.back();
            } else {
                copy(i, j);
            }
            i = j;
        } else {
            copy(i, i + 1);
            ++i;
        }
    }
    return out;
}

bool isBuiltinUniform(const std::string& name) {
    return std::any_of(std::begin(kBuiltins), std::end(kBuiltins),
                       [&](const BuiltinUniform& b) { return name == b.name; });
}

}  // namespace pg::shader
